# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  cabocha = {
    pname = "cabocha";
    version = "96e100a62f6dadceb490cdd61c8c15fb561f6674";
    src = fetchFromGitHub {
      owner = "taku910";
      repo = "cabocha";
      rev = "96e100a62f6dadceb490cdd61c8c15fb561f6674";
      fetchSubmodules = false;
      sha256 = "sha256-IlqOZTy+qmeZXpeUuMUBMyAIlKez/EmfUvr10NP1+84=";
    };
    date = "2025-02-22";
  };
  crfpp = {
    pname = "crfpp";
    version = "c603ea6fc2cc8e5317d2754971bc787da383f7e5";
    src = fetchFromGitHub {
      owner = "taku910";
      repo = "crfpp";
      rev = "c603ea6fc2cc8e5317d2754971bc787da383f7e5";
      fetchSubmodules = false;
      sha256 = "sha256-y6jSjy7svDaCEJs7aoREhD9i4sJjhhEcInSnzf8frOI=";
    };
    date = "2025-02-22";
  };
}
