pluginGroup = dev.t3tra.mozuku.idea
pluginName = MoZuku
pluginRepositoryUrl = https://github.com/t3tra-dev/MoZuku
pluginVersion = 0.1.0

pluginSinceBuild = 252
platformVersion = 2025.2.6.1

platformPlugins =
platformBundledPlugins =
platformBundledModules =

gradleVersion = 9.4.1

org.gradle.configuration-cache = true
org.gradle.caching = true
